apiVersion: v1
items:
  - apiVersion: v1
    data:
      password: ENC[AES256_GCM,data:8nqpBvRJtU8=,iv:+PyBInMdBfproysG/qM8qWg6lcS+Vl4QRzzESPrPzis=,tag:kmlyMOLYdSqPgq0QzRci1A==,type:str]
      user: ENC[AES256_GCM,data:DwSWjZGG50Y=,iv:so3FRDqyX6hflQmzz63xEKBi0StwqQXlV6s05ErsSuc=,tag:RRBdxwwiUrNWoVB8inq7YQ==,type:str]
    kind: Secret
    metadata:
      labels:
        kustomize.toolkit.fluxcd.io/name: apps
        kustomize.toolkit.fluxcd.io/namespace: flux-system
      name: test-secret
    type: Opaque
  - apiVersion: v1
    data:
      credentials.json: ENC[AES256_GCM,data:/oovp4pf1u/NDxdLfJibvKG9xlCZGptsRL02SPB8J6t80ncjdyzmM0GbXdShdGVs9Jp4Aq5L9un70iVq3RzCpLJ8by78kosGLAzKLQ+1h2UMZ8mErVXLd++M8ABQXPi+g0QjLjxGiuW9IgQGaGrqyY1w7XOBr23W7Zqw5ft3GZe5AfLzbkoR5P67qM3M4JrQqJBjllpRJl2bxsHKPjQdXARmhINLaCFXjIlZsEzrfGHMDOEyMgRqWI47eiRJBED9T5ubwzMCh+FwXvY41Fg1wmEXm/sYjycM,iv:ApJnYG1KuCic17eqNgofHggTwQFdeKUee1Ddwj6j4Xk=,tag:La5Mlue89VxlhBjivmp/WA==,type:str]
    kind: Secret
    metadata:
      name: tunnel-credentials
    type: Opaque
kind: List
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age13xkv5nawtjejeqtphjcmw97maw7v6d7ut7j982cxcv3epaw729csx5un2c
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxd1ZGTkc0aFI5SXc2UDBm
        cHBydHJ1SGRjc1FDTXJ2YlFNeFByTXU3VzB3CjdjM2Z0TGg2RGNLenZSTGJrMU5O
        SlJBUnMreTF4NzEvNG9lNW5zVmdWV2cKLS0tIDZBVzFRNVN1eU55RjlYeGFSVEZY
        YnRrSFpGVXR3RVlxMGkwV1hWaVM5a0EKXYZdoEEnA9mGbJidjzDeK48zi38wW5pg
        xz75xXMvnZvNMOgrsR3Sruwpl6CpwEzPqLbihDkRXKRR2IyXZ0CdYQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2024-12-04T03:17:38Z"
  mac: ENC[AES256_GCM,data:BLIIAPgcc9I3f89OJVJwA3sbwO6PZhyHm1sNBryxftZ1dkNv9p94TbhHajCLYmcHpZst1pJv8cVlxaVWwJymXTokSzBgyeYlFVG8O5WXot6//fWfQn9mLNLuHv9qcjl6nWt3z9tYXfnjqvYokMmL2DYUowDlWom73UNYiFvwTR4=,iv:mHiuQ16OLI0FNcphjHCVuzU/E2GRrZ00VSIKrm2szw4=,tag:DhbQkmYjBLEFUs7RxVyO0g==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  version: 3.9.2
